#!/bin/bash

set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <parameter-group-1> <parameter-group-2>"
  exit 1
fi

GROUP1="$1"
GROUP2="$2"

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

aws rds describe-db-cluster-parameters \
  --db-cluster-parameter-group-name "$GROUP1" \
  --query "Parameters[].[ParameterName, ParameterValue]" \
  --output json > "$TMP_DIR/group1.json"

aws rds describe-db-cluster-parameters \
  --db-cluster-parameter-group-name "$GROUP2" \
  --query "Parameters[].[ParameterName, ParameterValue]" \
  --output json > "$TMP_DIR/group2.json"

jq -r '.[] | @tsv' "$TMP_DIR/group1.json" | sort -k1,1 > "$TMP_DIR/group1.tsv"
jq -r '.[] | @tsv' "$TMP_DIR/group2.json" | sort -k1,1 > "$TMP_DIR/group2.tsv"

echo -e "Parameter\t$GROUP1\t$GROUP2"

join -t $'\t' -a 1 -a 2 -e "<none>" -o auto "$TMP_DIR/group1.tsv" "$TMP_DIR/group2.tsv" |
  awk -F $'\t' '$2 != $3 { printf "%-40s %-30s %-30s\n", $1, $2, $3 }' |
  column -t
